# Generated by Django 2.2 on 2019-12-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_basket_basketline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketline',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketline',
            name='product',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketLine',
        ),
    ]
